spring.application.name=spring-desde-0
spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://ep-blue-thunder-act5fj4q-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ArhuqRZXn56d
spring.datasource.driver-class-name=org.postgresql.Driver
