spring.application.name=spring-desde-0
spring.threads.virtual.enabled=true

# URL A LA BASE DE DATOS
spring.datasource.url=jdbc:postgresql://ep-blue-thunder-act5fj4q-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#Username
spring.datasource.username=neondb_owner
#Password
spring.datasource.password=npg_ArhuqRZXn56d
# Pool de hilos
spring.datasource.hikari.maximum-pool-size=10
# Timeour
spring.datasource.hikari.connection-timeout=2000
#Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# que es HIKARI? es un gestor de conecciones hacia la base de datos

# Inicializacion del a db - toma de resources los archivos schema.sql y data.sql
spring.sql.init.mode=always